# Generated by Django 3.0.3 on 2020-06-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
    ]
