# Generated by Django 3.0.3 on 2020-06-25 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ressys', '0004_auto_20200625_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 16, 14, 4, 418317, tzinfo=utc)),
        ),
    ]
